/*
	#author		lut000
	#date 		2017/10/20
	#purpose	路由
*/
define(["app"],function(app){
    return app.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){
    	$urlRouterProvider.otherwise('home');
    	var ntimes=(new Date()).getTime();
    	$stateProvider
	    	//views部分
			.state("view",{
				url:"/view",
				templateUrl:"view.html?t="+ntimes,
				controller:"viewController"
			})
			//首页
    		.state("home",{
    			url:"/home",
    			templateUrl:"home.html?t="+ntimes,
    			controller:"homeController"
    		})
    		.state("service",{
    			url:"/service",
    			templateUrl:"service.html?t="+ntimes,
    			controller:"serviceController"
    		})
    		.state("partner",{
    			url:"/partner",
    			templateUrl:"partner.html?t="+ntimes,
    			controller:"partnerController",
    			views:{
					//默认进入后的配置
	                "":{
	                	templateUrl:"partner.html?t="+ntimes,
	                    controller:"partnerController",
	                }
	            }
    		})
    		.state("partner.list",{
				url:"/list",
				templateUrl:"partner/list.html?t="+ntimes,
				controller:"partnerController.listController"
			})
			.state("partner.story",{
				url:"/story",
				templateUrl:"partner/story.html?t="+ntimes,
				controller:"partnerController.storyController"
			})
			.state("about",{
				url:"/about",
				templateUrl:"about.html?t="+ntimes,
				controller:"aboutController",
				view:{
					"":{
						templateUrl:"about.html?t="+ntimes,
						controller:"aboutController"
					}
				}
			})
			.state("about.1",{
				url:"/1",
				templateUrl:"about/introduction.html?t="+ntimes,
				controller:"aboutController.introductionController"
			})
			.state("about.2",{
				url:"/2",
				templateUrl:"about/culture.html?t="+ntimes,
				controller:"aboutController.cultureController"
			})
			.state("about.3",{
				url:"/3",
				templateUrl:"about/honours.html?t="+ntimes,
				controller:"aboutController.honoursController"
			})
			.state("about.4",{
				url:"/4",
				templateUrl:"about/news.html?t="+ntimes,
				controller:"aboutController.newsController"
			})
			.state("view.news_detail",{
				url:"/news_detail",
				templateUrl:"about/news-detail.html?t="+ntimes,
				controller:"viewController.newsDetailController"
			})
			.state("about.5",{
				url:"/5",
				templateUrl:"about/development.html?t="+ntimes,
				controller:"aboutController.newsController"
			})
			.state("about.6",{
				url:"/6",
				templateUrl:"about/photos.html?t="+ntimes,
				controller:"aboutController.photosController"
			})
			.state("view.photo_detail",{
				url:"/photo_detail",
				templateUrl:"about/photo-detail.html?t="+ntimes,
				controller:"viewController.photosDeatailController"
			})
			.state("about.7",{
				url:"/7",
				templateUrl:"about/recruit.html?t="+ntimes,
				controller:"aboutController.recruitController"
			})
			.state("contact",{
				url:"/contact",
				templateUrl:"contact.html?t="+ntimes,
				controller:"contactController",
				view:{
					"":{
						templateUrl:"contact.html?t="+ntimes,
						controller:"contactController"
					}
				}
			})
			.state("contact.site",{
				url:"/site",
				templateUrl:"contact/service-site.html?t="+ntimes,
				controller:"contactController.siteController"
			})
			.state("contact.cooperation",{
				url:"/cooperation",
				templateUrl:"contact/cooperation.html?t="+ntimes,
				controller:"contactController.cooperationController"
			})
			.state("contact.advertisement",{
				url:"/advertisement",
				templateUrl:"contact/advertisement.html?t="+ntimes,
				controller:"contactController.advertisementController"
			})
    		//底部会员相关
			.state("member",{
				url:"/member",
				templateUrl:"member.html?t="+ntimes,
				controller:"memberController",
				view:{
					"":{
						templateUrl:"member.html?t="+ntimes,
						controller:"memberController"
					}
				}
			})
			.state("member.notes",{
				url:"/notes",
				templateUrl:"member/notes.html?t="+ntimes,
//				controller:"memberController.notesController"
			})
			.state("member.become",{
				url:"/become",
				templateUrl:"member/become.html?t="+ntimes,
//				controller:"memberController.becomeController"
			})
			.state("member.cost",{
				url:"/cost",
				templateUrl:"member/cost.html?t="+ntimes,
//				controller:"memberController.costController"
			})
			.state("member.paytype",{
				url:"/paytype",
				templateUrl:"member/paytype.html?t="+ntimes,
//				controller:"memberController.paytypeController"
			})
			.state("member.free_experience",{
				url:"/free-experience",
				templateUrl:"member/free-experience.html?t="+ntimes,
//				controller:"memberController.freeExperienceController"
			})
			//常见问题
			.state("view.faq",{
				url:"/faq",
				templateUrl:"pop-help/pop-help.html?t="+ntimes,
				controller:"viewController.faqController"
			})
			
			//登录注册
			.state("login",{
				url:"/login",
				templateUrl:"login/login.html?t="+ntimes,
				controller:"loginController"
			})
			.state("register",{
				url:"/register",
				templateUrl:"login/register.html?t="+ntimes
			})
			.state("forget_password",{
				url:"/forget-password",
				templateUrl:"login/forget-password.html?t="+ntimes
			})
    }])
});